version: "3.0"

volumes:
  jc_mysqldata:
  jc_esdata:

services:

  # https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html
  # https://github.com/k-int/KBPlusG3/blob/dev-integration/SETUP-ES-DOCKER.txt
  # https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  jc_es6:
    container_name: jc_es6
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    restart: 'no'
    environment:
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - cluster.name=elasticsearch
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200 
    volumes:
      - jc_esdata:/usr/share/elasticsearch/data
    networks:
      default:
        aliases:
          - eshost
          - elasticsearch

  # Connect with mysql --protocol=tcp -h localhost -u k-int -p kbplus700dev
  jc_mysql:
    container_name: jc_mysql
    image: mariadb:11
    restart: 'no'
    environment:
      MYSQL_ROOT_PASSWORD: jc
      MARIADB_USER: admin
    volumes:
      - jc_mysqldata:/var/lib/mysql
      - ./mysqlinit:/docker-entrypoint-initdb.d
    healthcheck:
      interval: 30s
      retries: 3
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 30s
    ports:
      - 3306:3306
